<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  

  <xacro:macro name="wheel" params="side parent xyz rpy radius steering">   

    <xacro:property name="mount_size" value="0.01" />
    <xacro:property name="steering_length" value="0.03" />
    <xacro:property name="steering_radius" value="0.005" />
    <xacro:property name="axis_length" value="0.01" />
    <xacro:property name="axis_radius" value="0.01" />
    <xacro:property name="wheel_length" value="0.026" />
    <xacro:property name="wheel_radius" value="${radius}" />
    <xacro:property name="cap_size" value="0.01" />
    <xacro:property name="cap_length" value="0.005" />
    
    <!-- Mount -->
    <joint name="wheel_mount_${side}_joint" type="${steering}">  <!--fixed/revolute -->
        <origin xyz="${xyz}" rpy="${rpy}"/>
        <parent link="${parent}"/>
        <child link="wheel_mount_${side}"/>
        <axis xyz="0 1 0"/>
        <limit effort="50" velocity="50" lower= "${-M_PI}" upper="${M_PI}" />
    </joint>
    <link name="wheel_mount_${side}">
        <visual>
            <origin xyz="0 0 ${mount_size/2}" rpy="0 0 0"/>
            <geometry> 
                <box size="${mount_size} ${mount_size} ${mount_size}"/>
            </geometry>
        </visual>
    </link>
    
    <!-- steering -->
    <joint name="wheel_steering_${side}_joint" type="fixed">
        <origin xyz=" 0 0 0" rpy="0 0 0"/>
        <parent link="wheel_mount_${side}"/>
        <child link="wheel_steering_${side}"/>
    </joint>
    <link name="wheel_steering_${side}">
        <inertial>
            <mass value="0.001"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="0.012411765597" ixy="0" ixz="0" iyy="0.015218160428" iyz="0" izz="0.011763977943"/>
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <geometry> 
                <cylinder radius="${steering_radius}" length="${steering_length}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <geometry> 
                <cylinder radius="${steering_radius}" length="${steering_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial_with_origin radius="${axis_radius}" length="${steering_length}"  mass="0.001">
            <origin xyz="0 0 ${steering_radius/2}" rpy="0 0 0"/>
        </xacro:cylinder_inertial_with_origin>
    </link>
    
    <!-- axis -->
    <joint name="wheel_axis_${side}_joint" type="continuous">
        <origin xyz=" 0 0 ${steering_radius}" rpy="0 0 0"/>
        <parent link="wheel_steering_${side}"/>
        <child link="wheel_axis_${side}"/>
        <axis xyz="0 0 1"/>
          <dynamics damping="0.000" friction="0.0"/>
    </joint>
    <link name="wheel_axis_${side}">
        <visual>
            <origin xyz="0 0 ${axis_length/2}" rpy="0 0 0"/>
            <geometry> 
                <cylinder radius="${axis_radius}" length="${axis_length}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 ${axis_length/2}" rpy="0 0 0"/>
            <geometry> 
                <cylinder radius="${axis_radius}" length="${axis_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial_with_origin radius="${axis_radius}" length="${axis_length}"  mass="0.0875">
            <origin xyz="0 0 ${axis_length/2}" rpy="0 0 0"/>
        </xacro:cylinder_inertial_with_origin>
    </link>
  
    <!-- Wheel -->
    <joint name="wheel_${side}_joint" type="fixed">
        <origin xyz=" 0 0 ${axis_length}" rpy="0 0 0"/>
        <parent link="wheel_axis_${side}"/>
        <child link="wheel_${side}"/>
    </joint>
    <link name="wheel_${side}">
        <visual>
            <origin xyz="0 0 ${wheel_length/2}" rpy="0 0 0"/>
            <geometry> 
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 ${wheel_length/2}" rpy="0 0 0"/>
            <geometry> 
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial_with_origin radius="${wheel_radius}" length="${wheel_length}"  mass="0.026">
            <origin xyz="0 0 ${wheel_length/2}" rpy="0 0 0"/>
        </xacro:cylinder_inertial_with_origin>
    </link>
    
    <!-- Wheel Cap -->
    <joint name="wheel_cap_${side}_joint" type="fixed">
        <origin xyz=" 0 0 ${wheel_length}" rpy="0 0 0"/>
        <parent link="wheel_${side}"/>
        <child link="wheel_cap_${side}"/>
    </joint>
    <link name="wheel_cap_${side}">
        <visual>
            <origin xyz="0 0 ${cap_length/2}" rpy="0 0 0"/>
            <geometry> 
                <box size="${cap_size} ${cap_size} ${cap_length}"/>
            </geometry>
        </visual>
    </link>
  
  
  </xacro:macro>

</robot>
